config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :tasks

  post 'auth_user' => 'authentication#authenticate_user'
  root to: 'visitors#index'

  # api routes
  namespace :api do
    namespace :v1 do
      resources :tasks
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  
  #associations
  belongs_to :user

  # required fields validation
  validates :name,:start_time,:end_time,:path,presence: true

  # selected days are array of integers
  # it will retrieve day names of selected days
  def scheduled_days
    day_names = []
    if days.any?
      days.each do |index|
        day_names << Date::DAYNAMES[index]
      end
    end
    day_names
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name,:email,presence: true
  has_many :tasks,dependent: :destroy
end

app/controllers/api/v1/base_api_controller.rb
class Api::V1::BaseApiController < ApplicationController
  protect_from_forgery with: :null_session
  # before action, check if user is authenticated
  before_action :authenticate_request!
  
  attr_reader :current_user

  

  protected
    
    ## check if user is authenticated
    ## otherwise, return json of Not Authenticated
    def authenticate_request!
      unless user_id_in_token?
        render json: { errors: ['Not Authenticated'] }, status: :unauthorized
        return
      end
      @current_user = User.find(auth_token[:user_id])
    rescue JWT::VerificationError, JWT::DecodeError
      render json: { errors: ['Not Authenticated'] }, status: :unauthorized
    end

    private
      
      ## check Authorization token in headers
      ## and, get last part of token 
      def http_token
        @http_token ||= if request.headers['Authorization'].present?
          request.headers['Authorization'].split(' ').last
        end
      end

      ## decoding http token using JWT
      ## returns decoded token
      def auth_token
        @auth_token ||= JsonWebToken.decode(http_token)
      end

      ## check if user id in decoded token
      def user_id_in_token?
        http_token && auth_token && auth_token[:user_id].to_i
      end

end

app/controllers/api/v1/tasks_controller.rb
class Api::V1::TasksController < Api::V1::BaseApiController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  #########################################
  ## url: /api/v1/tasks
  ## method: GET
  ## Headers: [Authorization: token]
  ## returns array of tasks in json format
  ##########################################
  def index
    @tasks = current_user.tasks.all
  end

  ###########################################
  ## url: /api/v1/tasks/1
  ## method: PATCH
  ## Headers: [Authorization: token]
  ## returns task object if saved.
  ## Otherwise, returns errors in json format
  ############################################
  def update
    if @task.update(task_params)
      render :show, status: :ok, location: @task
    else
      render json: @task.errors, status: :unprocessable_entity
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:is_executed)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  # skip token authenticity during authenticate user
  skip_before_action :verify_authenticity_token,only: :authenticate_user

  ## authenticate user with valid email & password
  ## returns user payload with auth token if valid email/password
  ## Otherwise, return error 'Invalid Username/Password' in json format
  
  def authenticate_user
    user = User.find_for_database_authentication(email: params[:email])
    if user and user.valid_password?(params[:password])
      render json: payload(user)
    else
      render json: {errors: ['Invalid Username/Password']}, status: :unauthorized
    end
  end

  private

  # returns user payload with encrypted auth token.
  def payload(user)
    return nil unless user and user.id
    {
      auth_token: JsonWebToken.encode({user_id: user.id}),
      user: {id: user.id, email: user.email}
    }
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = current_user.tasks.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new(user: current_user)
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        # update days
        update_days(@task,params[:task][:days].split(','))
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        # update days
        update_days(@task,params[:task][:days].split(','))
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :start_time, :end_time, :path,:days,:user_id)
    end

    def update_days task,days_array
      task.update(days: days_array)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to root_path, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-dismissible alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/_sidebar.slim
#sidebar-wrapper
  ul.sidebar-nav
    - if user_signed_in?
      li
        = link_to "Dashboard",root_path
      li
        = link_to "Tasks",tasks_path
      li
        = link_to 'Signout', destroy_user_session_path, :method=>'delete'
    - else
      li
        = link_to 'Signin', new_user_session_path
      li
        = link_to "Signup",new_user_registration_path
      li
        = link_to "Forgot Password",new_user_password_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Client Server App'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Client Server App'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => 'reload'
    == javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      #wrapper
        = render 'layouts/sidebar'
        = render 'layouts/messages'
        #page-content-wrapper
          .container-fluid        
            == yield

    
    = include_rails_script

app/views/tasks/_form.slim
= form_for @task,html:{id: "task_form"} do |f|
  - if @task.errors.any?
    #error_explanation
      h2 = "#{pluralize(@task.errors.count, "error")} prohibited this task from being saved:"
      ul
        - @task.errors.full_messages.each do |message|
          li = message

  = f.hidden_field :user_id
  .form-group
    = f.label :name
    = f.text_field :name,class: "form-control"
  .form-group
    = f.label :start_time
    = f.datetime_select :start_time,class: "form-control"
  .form-group
    = f.label :end_time
    = f.datetime_select :end_time,class: "form-control"
  .form-group
    = f.label :file_path
    = f.text_field :path,class: "form-control"
  .form-group
    .row
      - Date::DAYNAMES.each_with_index do |v,i|
        .col
          = f.label "#{v}"
          = check_box_tag "task[#{i}]",i,@task.days.try(:include?,i),class: "days_names"
      = f.hidden_field :days
  .actions = f.submit

app/views/tasks/edit.slim
h1 Editing task

== render 'form'

=> link_to 'Show', @task
'|
=< link_to 'Back', tasks_path

app/views/tasks/index.html.slim
h1 Listing tasks

table
  - if @tasks.any?
    thead
      tr
        th Name
        th Start time
        th End time
        th Path
        th
        th

    tbody
      - @tasks.each do |task|
        tr
          td = task.name
          td = task.start_time.strftime("%d/%m/%Y %H:%M")
          td = task.end_time.strftime("%d/%m/%Y %H:%M")
          td = task.path
          td = link_to 'Edit', edit_task_path(task)
          td = link_to 'Destroy', task, data: { confirm: 'Are you sure?' }, method: :delete
  - else
    tr
      td No task found.

br

= link_to 'New Task', new_task_path,class: "btn btn-default"

app/views/tasks/new.slim
h1 New task

== render 'form'

= link_to 'Back', tasks_path

app/views/tasks/show.html.slim
p#notice = notice

p
  strong Name:
  = @task.name
p
  strong Start time:
  = @task.start_time
p
  strong End time:
  = @task.end_time
p
  strong Path:
  = @task.path

=> link_to 'Edit', edit_task_path(@task)
'|
=< link_to 'Back', tasks_path

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.slim
.row
  .col-lg-12
    h1 Simple Sidebar
    p This template has a responsive menu toggling system. The menu will appear collapsed on smaller screens, and will appear non-collapsed on larger screens. When toggled using the button below, the menu will appear/disappear. On small screens, the page content will be pushed off canvas.
    a#menu-toggle.btn.btn-default href="#menu-toggle"  Toggle Menu